### ISSUE TITLE
Ability to disable SEOPro for specified resources

### ISSUE THREAD

**Issue by vierkantemeter** [Sterc/SEOPro#36]
Some of my resources don't need SEOPro, for example I have a settings page that is just used for settings and not displayed on frontend. It would be great if we could disable SEOPro for certain resources, for example by means of a system setting where you could enter the IDs of the resources to be excluded.

**Comment by vierkantemeter** [comment]
Sorry for my late reply, I had a child in the meantime :-D 

I'm running into this again. It would be great if we could enable/disable on all the fields you mention!

**Comment by Jako** [comment]
Disable on template base could be done with https://github.com/Jako/SEOPro/commit/a21e4cfcf0b2611aed940ec4e96fc175db5b428f

**Comment by vierkantemeter** [comment]
Thanks!
