### ISSUE TITLE
Inherit settings for children

### ISSUE THREAD

**Issue by crimsonpixel** [Sterc/SEOPro#38]
Don't think you can already set this but it would be a great feature to add to SEOPro - the ability for child resources to inherit parent settings especially useful if you have an area that you don't want to be listed in xml sitemap because they are in a "members" area.

**Comment by joeke** [comment]
I think your mistaking SEOPro and SEOTab.. SEOTab has the settings for visibility in sitemaps. For more info see https://github.com/Sterc/SEOTab
