### ISSUE TITLE
[Enhancement] Create setting for excluding certain template ID's from using SEOpro

### ISSUE THREAD

**Issue by hugopeek** [Sterc/SEOPro#43]
(I don't know if this is possible right now, sorry if I missed it..)

Although it's great to have on all your content-related resources, sometimes there's other types of resources that don't require the SEOpro plugin to be loaded. It would be nice if you could exclude those resources somehow. Think the best way is by template ID, but other options might also be relevant.

**Comment by vierkantemeter** [comment]
+1

**Comment by vierkantemeter** [comment]
It's possible to exclude it by template. See https://github.com/Sterc/SEOPro/issues/36

**Comment by joeke** [comment]
Yes this is possible in latest versions with system setting 'seopro.disabledtemplates'. Closing this issue for now.

**Comment by bwente** [comment]
How about disabled on the "empty" template? I use the empty template for content used in other resources. It might confuse an over eager SEO specialist.
