### ISSUE TITLE
Option to rename "301 Redirect" section to just "Redirects"

### ISSUE THREAD

**Issue by adamwintle** [Sterc/SEOPro#45]
Today a client got very confused by the 301 Redirect section of this plugin, she literally was reading it like "three hundred and one redirects"; to keep things as client friendly as possible it would be to have an option to name the section just "Redirects"?

Maybe this could be managed in the SEOPro Lexicons?

**Comment by Bumme** [comment]
Hello adam,

I think you mean the 301 section from SEOtab (https://github.com/Sterc/SEOTab)
All the texts are in lexicons so you could rename it for your client.
