### ISSUE TITLE
Google Preview shows false information if you duplicate a resource

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/SEOPro#47]
![screen shot 2015-09-02 at 14 43 40](https://cloud.githubusercontent.com/assets/447453/9631436/23a80660-5181-11e5-9c01-d584574198b5.png)

MODX 2.4, SeoPro 1.0.4

**Comment by Bumme** [comment]
Do you've got any console errors?

**Comment by joeke** [comment]
Hi @sonicpunk 
Do you still have this issue? If so, does it still show false information after a save and reload? If not it could be a caching issue, or indeed as Bumme mentioned a JS error which should popup in your browser console.

**Comment by sonicpunk** [comment]
Hi, sorry about my post here.  What had happened was that I had entered a title in the longtitle field before I hide it using form customization.  The SEO extra read this out of the database, so my changes in the title field did not register in the Google preview box.  It seemed to be a problem with my execution and not with the SEO tool itself.  I forgot to close this.
