### ISSUE TITLE
Wrong character count when show site title in description is off

### ISSUE THREAD

**Issue by gleighfield** [Sterc/SEOPro#48]
After setting the seopro.usesitename setting to NO, when editing a resource, the pagetitle/longtitle field total number of characters left, still reflects the site_name setting.

**Comment by joeke** [comment]
Hi @gleighfield,
We'll look into this issue and fix it in the next release.
Thank you!

**Comment by joeke** [comment]
Should be fixed with https://github.com/Sterc/SEOPro/commit/8b5ed72b4005ee2845ea640ea99ad10706eb49f8
