### ISSUE TITLE
Undefined index: template

### ISSUE THREAD

**Issue by christianseel** [Sterc/SEOPro#50]
Is there any szenario where a frontend request (`OnLoadWebDocuement`) would contain a template param in the `$_REQUEST` array?

https://github.com/Sterc/SEOPro/blob/master/core/components/seopro/elements/plugins/seopro.plugin.php#L114

```
Array
(
    [content] => [2016-01-19 18:13:04] (WARN @ /core/cache/includes/elements/modplugin/2.include.cache.php : 114) PHP notice: Undefined index: template

    [level] => WARN
    [msg] => PHP notice: Undefined index: template
    [def] => 
    [file] =>  @ /core/cache/includes/elements/modplugin/2.include.cache.php
    [line] =>  : 114
)
```

**Comment by joeke** [comment]
Hi @christianseel 
Good point, I can't think of any scenario where it would use the template url parameter on frontend. Looks like a copy/paste issue from the other (mgr) system events.
