### ISSUE TITLE
Getting "thumb down" on Description field despite containing focus keywords.

### ISSUE THREAD

**Issue by jeffmiranda** [Sterc/SEOPro#51]
Hi Sterc!

I'm receiving a strange behaviour. Perhaps it's a bug or maybe I'm not understanding how Focus Keywords works.

Note the thumbs down for the Description field in the following picture:
![image](https://cloud.githubusercontent.com/assets/5000958/12733486/5ea95c66-c8f8-11e5-81e8-5e9212db84a2.png)

Now if I change "construction" to simply "construct" I get a thumbs up:
![image](https://cloud.githubusercontent.com/assets/5000958/12733525/8c2313f8-c8f8-11e5-9b27-5cb0d0cd1f1f.png)

Is this the correct behaviour? If so, can someone please explain it to me?

Thanks!

**Comment by crimsonpixel** [comment]
Hmm - this seems to be an issue with me too.  Using Rev 2.4.2 and SEO Pro 1.0.4.  Perhaps some further documentation would be useful....

**Comment by digitalpenguin** [comment]
Me too, seems to happen if all keywords are used.

**Comment by gpsietzema** [comment]
Might be because of uppercase/lowercase.

**Comment by joeke** [comment]
@jeffmiranda This has to do with the fact that the keyword checker only gives a thumbs-up when a maximum of 4 focus keywords are used in your title / description. I'm not quite sure why this limit exists; could be to prevent users from 'keyword stuffing' their titles. But I think it's safe to remove or raise this limit as I think 4 is a bit too low.. @gpsietzema what are your thoughts on this?

**Comment by gpsietzema** [comment]
To be honest, I would never go for more than 3 for a single page... There will be a lot of different opinions on this though, so we could make it a system setting.

**Comment by joeke** [comment]
@gpsietzema Yes for a title a max of 3 or 4 will be OK I guess. But for the description (160 chars) the limit can be removed, don't you think?

**Comment by joeke** [comment]
I've added system settings for the maximum keyword amount for title and description. Also I've added a keyword counter to the keywords label. https://github.com/Sterc/SEOPro/commit/48d7964a35312470798faec67676c1e76bf70f3c and https://github.com/Sterc/SEOPro/commit/f3be6b5bde69d285b66ece5d7ba5368883d91532
