### ISSUE TITLE
Wrong number of characters in pagetitle and introtext

### ISSUE THREAD

**Issue by arimanr** [Sterc/SEOPro#57]
with an empty value indicates the 33 characters instead of zero.

PrntScrn ---> http://prnt.sc/e0kzoy

In descrition is doing great

**Comment by joeke** [comment]
@arimanr This has to do with that the site_name system-/context-setting gets added to the count. With commit https://github.com/Sterc/SEOPro/commit/8b5ed72b4005ee2845ea640ea99ad10706eb49f8 and by setting the system setting `seopro.usesitename` to 'No' the count should be correct.
