### ISSUE TITLE
Warning into seoPro plugin

### ISSUE THREAD

**Issue by Sergspm** [Sterc/SEOPro#59]
PHP notice: Undefined index: template
seoPro plugin, line 114
`$template = ($modx->resource->get('template')) ? (string)$modx->resource->get('template') : (string)$_REQUEST['template'];`
Version of seoPro: 1.0.4

**Comment by joeke** [comment]
Should be fixed with https://github.com/Sterc/SEOPro/commit/07187f3c8f2e5f13c83724c73460cf5fbaf59aa8
