### ISSUE TITLE
Include keywords in search?

### ISSUE THREAD

**Issue by bwente** [Sterc/SEOPro#60]
I would like to be able to include SEO focus keywords into SimpleSearch. But it isn't TV.
```
&includeTVs=`1`
&includeTVList=`seoPro.keywords`
```

**Comment by gpsietzema** [comment]
@bwente We just found out this is already possible by using the customPackages parameter of SimpleSearch. Example: 

`&customPackages=`seoKeywords:keywords:seopro:{core_path}components/seopro/model/:seoKeywords.resource = modResource.id``

**Comment by bwente** [comment]
Do you have to use ``&docFields=`keywords`` ? To get this to work?
