### ISSUE TITLE
Not seeing the Yandex emoticon

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOPro#61]
It's not a 404-image or something, it just isnt in the code, see screenshot.
![screen shot 2017-05-03 at 15 48 08](https://cloud.githubusercontent.com/assets/381017/25663434/f870e6ca-3017-11e7-9bcd-0799ac01a8e0.png)

**Comment by joeke** [comment]
Should be fixed with https://github.com/Sterc/SEOPro/commit/42d4556c54f63d7f29739e9b4c38f13b7c859a28
