### ISSUE TITLE
seopro.fields doesn't support link_attributes

### ISSUE THREAD

**Issue by jonleverrier** [Sterc/SEOPro#68]
I'm trying to add link_attributes to the list of supported seopro.fields, however it doesn't seem to be supported (doesn't show the thumbs up/down panel above the field in the manager).

I've re-purposed this field for custom page titles that don't follow the site default as per the idea in #25 

I'm using this setup in my page title:
```
[[*link_attributes:isempty=`[[*pagetitle:htmlentities]] | [[++site_seo_pagetitle:htmlentities:isempty=`[[++site_name:htmlentities]]`]]`]]
```

Is this by design?

**Comment by MrRoco** [comment]
Hello,
The link attributes field is supported with SeoPro.
The field should be set as following in the system setting: 

- link-attributes
