### ISSUE TITLE
Letter/Char counts are not updating in MODx 2.5.8

### ISSUE THREAD

**Issue by travisbotello** [Sterc/SEOPro#69]
The letter/char count is not updating anymore for pagetitle and longtitle fields. It is still working in description fields.

This issue occured after updating to MODx 2.5.8 with SEOPro 1.2.1

![screenshot 2017-10-11 14 07 48](https://user-images.githubusercontent.com/1157380/31439777-b6651090-ae8d-11e7-8162-b920ac95ef75.png)

**Comment by gpsietzema** [comment]
Thanks @travisbotello - Just tested and I can confirm this. We'll have a fix out asap!

**Comment by MrRoco** [comment]
@travisbotello The fix is out in version 1.2.2
