### ISSUE TITLE
Feature request: make description count available via setting ( < 300)

### ISSUE THREAD

**Issue by studiovlijmscherp** [Sterc/SEOPro#72]
Google seems to allow >155 (<300) characters for the meta description. Would be great if we could adjust the thresholds (by using custom property sets?)

**Comment by joeke** [comment]
Hi Michiel! 
There already is setting for that: `seopro.fields`. Here you determine which fields are checked by SeoPro, and the maximum desired length (after the colon `:`).

**Comment by MrRoco** [comment]
Hi Michiel,

Some extra information related to your issue.
As Joeke said, the setting is already there but currently the description field doesn't support a bigger entry then 255 chars based on the database setting the field has within MODx.

We have taken note of this and are looking for a solution for this.
