### ISSUE TITLE
Keywords not saved

### ISSUE THREAD

**Issue by funkyduke** [Sterc/SEOPro#73]
When creating a new page there's a zero (0) in the field. When typing something else in the field and saving, the resource saves correctly, but the keywords are not saved. When I go back to the resource the zero appears again. So I cannot fill in the keywords.

Modx 2.6.1. / PHP 7.2 / SeoPro 1.2.2.

![afbeelding](https://user-images.githubusercontent.com/1769979/35244170-8c53d22c-ffbf-11e7-9bdb-6ce9acd9dad4.png)

**Comment by degoya** [comment]
i can confirm this behavior on PHP 7.2.1

**Comment by MrRoco** [comment]
Hello,

I've added it to our backlog and w'ill look into it.

**Comment by funkyduke** [comment]
I can confirm that with PHP 7.1 (or below) there are no problems. So it's a PHP 7.2 issue.

**Comment by joeke** [comment]
This will be fixed in the upcoming 1.3.0 version.

**Comment by joeke** [comment]
And here it is: https://modx.com/extras/package/seopro
