### ISSUE TITLE
Unable to save a resource if the number of characters in a SEO Pro fields is larger than the default one

### ISSUE THREAD

**Issue by berj** [Sterc/SEOPro#77]
MODX 2.6.3

I upgrade to SEOPro 1.3.0, and now I am unable to save a resource if the number of characters in a SEO Pro fields is larger than the default one

Before the update I was able to save a resource when the number of characters was larger than the default one for the SEO Pro fields.

Is this normal, and should I change the default values for the SEO Pro fields? 

Thank

![error-on-saving](https://user-images.githubusercontent.com/7210511/39721085-46ea3808-520c-11e8-8cf9-a77494cd6eb8.png)

**Comment by fonpixel** [comment]
Yes, to prevent this restriction you should increase limits for each field. They placed in a system setting "seopro.fields"
![image](https://user-images.githubusercontent.com/25525060/40488476-87764586-5f6f-11e8-96b3-67c2dffca340.png)

**Comment by berj** [comment]
Thank you for your answer

**Comment by hugopeek** [comment]
I ran into this as well: https://github.com/Sterc/SEOPro/issues/78

Increasing those limits is a workaround, not a solution. There are still use cases where you'd want to keep the limit, but not strictly enforce it by preventing the user from saving the page.

**Comment by bwente** [comment]
My settings are not being respected.
```pagetitle:100,alias:50,description:180```
The description is stuck at 155.

**Comment by cercamon** [comment]
Same applies in my configuration. The ModX SEO Pro plugin gets in conflict with another plugin called Articles. In particular, the +pagetitle data field of an article can't be managed correctly when the two plugins are active. The character count and the length control of this data field completely fails when editing and updating an article.

We are using seopro-1.3.0-pl and articles-1.7.11-pl
![pagetitle2](https://user-images.githubusercontent.com/37086966/55682601-2b3c7800-5936-11e9-8bea-c1d5248b2b76.png)
![pagetitle](https://user-images.githubusercontent.com/37086966/55682602-2b3c7800-5936-11e9-9602-450be16bfdc0.png)
